import type { Metadata } from "next";
import "./globals.css";

import { Urbanist } from "next/font/google";
import { Noto_Sans_JP } from "next/font/google";

export const urbanist = Urbanist({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-urbanist",
  display: "swap",
});
export const notosansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-notosansjp",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
